version: '3.8'

volumes:
  test_volume:

services:
  mysql:
    image: mysql:latest
    container_name: food-order
    volumes:
      - test_volume:/var/lib/data
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=food-order
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:latest
    ports:
      - "6379:6379"